### ISSUE TITLE
Finalization stalling issues 2024-07

### ISSUE THREAD

**Issue by MOZGIII** [humanode-network/humanode#1104]
This is a tracking issue for the recurring finalization stalling incidents.

So far, here are the pointers we have.

Commits that are affecting the finalization directly:
- https://github.com/paritytech/substrate/pull/13289
  Should not the the cause though, as the issue is with the inability of grandpa to follow a reorg, which is cause by pruned blocks. Or, rather, it *could be the cause*, but this one is not really where the bug we'd like to fix is.
- https://github.com/paritytech/substrate/pull/13323 - ~~could this be the reason?~~ no, this one works as intended
- https://github.com/paritytech/substrate/pull/13364 - this looks like it directly messes with what's causing the bug, but more like it fixes the aftermath of the one above

Notable historical commits that might've affected this incident:
- https://github.com/paritytech/substrate/pull/12567
- https://github.com/paritytech/substrate/pull/11727 (unlikely though)
- https://github.com/paritytech/substrate/pull/13216 (actually looks somewhat interesting)
- https://github.com/paritytech/substrate/pull/13157 (maybe pinning the block that is used as a finality based is a good idea)

Probably irrelevant:
- https://github.com/paritytech/substrate/pull/13233
- https://github.com/paritytech/substrate/pull/13379
- https://github.com/paritytech/substrate/pull/1658
- https://github.com/paritytech/substrate/pull/11263
- https://github.com/paritytech/substrate/pull/13237
- https://github.com/paritytech/substrate/pull/13255

Related things from the future:
- https://github.com/paritytech/polkadot-sdk/pull/3962 - new fork pruning algorithm - might work better, but not sure
- https://github.com/paritytech/polkadot-sdk/issues/4903 - irrelevant for our issue, as this issue is with the new fork pruning algorithm mentioned above being too slow 

---

~~The thoughts we have so far is that the issue is caused by the broken block pruning (which is meaningful when an unfortunate best block selection happens).~~ (UPD: the blocks are not really pruned, we can still request them from the API; this means this is a selection issue) Grandpa tries to finalize the block that is pruned and not the part of the best chain anymore; upon receiving the precommits it fails to recognize them because the block can't be resolved (it's pruned). This is quite odd, since the nodes operate with `--blocks-pruning archive`, so it must mean they haven't seen the block in question as is it no never to be pruned if seen - but in reality we see a the reorg happening from the block in question to a new one, so the old block is definitely a known one.

---

We are currently on substrate 0.9.40.

---

Mainnet encountered this at least three times lately:

<img width="1662" alt="image" src="https://github.com/user-attachments/assets/87dd52d2-d2dc-4817-b425-00f1ebb8f09d">

**Comment by MOZGIII** [comment]
[Explore-logs-2024-07-26 10_41_41.txt](https://github.com/user-attachments/files/16388952/Explore-logs-2024-07-26.10_41_41.txt)
The logs from the node to hint what's going on

**Comment by MOZGIII** [comment]
Current plan for a workaround is to delay the finality for more than 2 blocks. Currently we are planning to delay the finality after by 5 blocks beyond the best block. This should help with reducing the chance of the reorg-caused race condition we are facing.

**Comment by MOZGIII** [comment]
We have analyzed the code, and it looks like the issue is with those two PRs:
- https://github.com/paritytech/substrate/pull/13289
- https://github.com/paritytech/substrate/pull/13364

The fix that is added at https://github.com/paritytech/substrate/pull/13364 does not apply after the code added at https://github.com/paritytech/substrate/pull/13289 returns an error. We'll investigate further.

We are still on course to apply the workaround mentioned above as a hotfix, but the long term solution is also in sight.

**Comment by MOZGIII** [comment]
To elaborate more on https://github.com/paritytech/substrate/pull/13364:

1. `LongestChain::finality_target` will error out when the passed target block is not in the best chain (https://github.com/paritytech/substrate/pull/13289/files#diff-97e7e3622ec6f0b455d18c1bf8055ccf5cfd210efd50348df6b07fce4531baeeR115-R119). This also applies to the case where the block number of the target and best-chain block are the same.
2. The fixup code at https://github.com/paritytech/substrate/pull/13364/files#diff-5ecb4cf31ed389a0d12482137c8b234485b199c200b09446cf8876321527446aR1242 tries to use the best block as target block (`best block to target block`) but in practice that part of the fn is not reached due to how an error from `LongestChain::finality_target` above is handled.

**Comment by bkchr** [comment]
> Added the test to reproduce the issue logic - [humanode-network/polkadot-sdk@master...humanode-network:polkadot-sdk:grandpa-voting-and-babe-reorg-race-condition](https://github.com/humanode-network/polkadot-sdk/compare/master...humanode-network:polkadot-sdk:grandpa-voting-and-babe-reorg-race-condition).

The test is succeeding?

**Comment by dmitrylavrenov** [comment]
> > Added the test to reproduce the issue logic - [humanode-network/polkadot-sdk@master...humanode-network:polkadot-sdk:grandpa-voting-and-babe-reorg-race-condition](https://github.com/humanode-network/polkadot-sdk/compare/master...humanode-network:polkadot-sdk:grandpa-voting-and-babe-reorg-race-condition).
> 
> The test is succeeding?

Yep, we've implemented it in the way to verify our thoughts about the happened case.

**Comment by dmitrylavrenov** [comment]
We met the same error

```
	// `hashof8_a` should be finalized next based on last completed round data,
	// but it's not an valid finality target
	assert_matches!(
		env.select_chain.finality_target(hashof8_a, None).await.unwrap_err(),
		ConsensusError::ChainLookup(_)
	);
```

**Comment by andresilva** [comment]
I have only looked into this superficially, but I think @MOZGIII comment on the `LongestChain::finality_target` issue is correct. The root cause is that we shouldn't error when the given vote target is not in the best chain, otherwise we make it impossible for finality to proceed in case we have a round estimate that gets re-orged out. In principle what should happen is grandpa would finalize the fork that got re-orged out, and then the node would re-org again (after grandpa finalizes). I didn't think through all the consequences of such a change.

**Comment by dmitrylavrenov** [comment]
> I have only looked into this superficially, but I think @MOZGIII comment on the `LongestChain::finality_target` issue is correct. The root cause is that we shouldn't error when the given vote target is not in the best chain, otherwise we make it impossible for finality to proceed in case we have a round estimate that gets re-orged out. In principle what should happen is grandpa would finalize the fork that got re-orged out, and then the node would re-org again (after grandpa finalizes). I didn't think through all the consequences of such a change.

The same thoughts we discussed with @MOZGIII

**Comment by dmitrylavrenov** [comment]
@bkchr @andresilva let me create PR of this test in our fork in describe it in more details

**Comment by andresilva** [comment]
https://github.com/paritytech/polkadot-sdk/pull/5153

I think this should fix it.

**Comment by MOZGIII** [comment]
https://github.com/paritytech/polkadot-sdk/pull/5153 looks good, thx!

This would still be risky to ship for us as it means the whole layer of logic dedicated to the grandpa-issued reorg was not used for a while not and may contain bugs or just be broken cause of being stale...

We'll think about how to test this. So far we have thought about replicating the scenario of having 1k+ validators on our load-test facilities - but in our prior load tests we haven't seen the finality stalls like we see in the live chain; that might be due to not running for enough time, or due to other conditions - so it unlikely we'll have an accurate test for this in the load testing environment.

Any thoughts on how to trigger this bug in the live-like environment?

**Comment by andresilva** [comment]
I think besides making any significant changes to make sure the issue happens (e.g. changing some voters to vote on abandoned forks explicitly), the easiest way would be to make forks more likely to happen and hence make it more likely for the issue to surface. I think changing `https://github.com/humanode-network/humanode/blob/master/crates/humanode-runtime/src/constants.rs#L49` to `(1, 1)` should make forks more prevalent, reducing block time might also help.

**Comment by MOZGIII** [comment]
Great idea! We will also change the block time from 6s to 1s for more stress...

---

Pretty sure it is fine, but just to double check - is it safe to ship https://github.com/humanode-network/humanode/commit/f5bccf0d13193e070aeef1472a2a4726e836cd93 ?
Should not cause anything problematic afaik.

**Comment by andresilva** [comment]
Yes, don't see any problem with that (and should make the issue less likely to happen). 

For the test above you can also remove this rule to make sure the validators always vote for the latest block, which should make issues with reorgs even more likely!

**Comment by MOZGIII** [comment]
Great!

To summarize, we'll test your fix with the following:
- `(1, 1)` primary at babe
- 1s block production time
- removed `BeforeBestBlockBy` at voting rules

**Comment by MOZGIII** [comment]
Some new input, as the chain stalled again just now:

- last finalized block 8745707 `0x3c97148e16cc04c5df90b96f64f37d9dddf083468a6c4df2dd447f5396df58fd`
- epoch start 8745697 `0xce0fac61989be9f69a27c5671e71b40f2adc579c231b933a613c5ab103fd5f7a` (10 blocks away)
- `Reorg on #8745708,0x191a…c58d to #8745711,0xfb9c…21bc, common ancestor #8745707,0x3c97…58fd` - to the future


<img width="1419" alt="image" src="https://github.com/user-attachments/assets/0bfe0350-5878-41d0-98fb-5b79a7e34253">


<img width="1628" alt="image" src="https://github.com/user-attachments/assets/c673c0fa-2f27-46aa-ba3e-a8602c61b3be">

**Comment by MOZGIII** [comment]
We did not push the fix just yet, only the bigger finalization delay

But we see this:

<img width="1625" alt="image" src="https://github.com/user-attachments/assets/681a4071-4176-44af-9ab0-61f3a26c8cbd">

The issue seems to be that once the prevote for a round goes out it then can't progress and the grandpa stalls.

@andresilva @bkchr let me know if you need access to our infra

**Comment by MOZGIII** [comment]
Maybe some peers are not voting in the round because of the bug (and some do - like the one we have above), and thus the whole consensus stalls, as if the amount of online nodes is less that quorum...

Only 39% of the nodes have applied the finality delay update - https://telemetry.humanode.io/#stats/0xc56fa32442b2dad76f214b3ae07998e4ca09736e4813724bfb0717caae2c8bee

**Comment by andresilva** [comment]
Yes, you'd need >2/3 of the nodes on the new version for it to effectively take effect.

**Comment by MOZGIII** [comment]
We are backporting the fix to our substrate fork; we are still working on reproducing the issue. @dmitrylavrenov will send an update when we have news on that front.

**Comment by dmitrylavrenov** [comment]
Were able to reproduce grandpa stuck with just 15 validators
- used https://github.com/humanode-network/humanode/pull/1106 image with agreed babe and grandpa params above
- run peers with the following additional params to make gossip longer in terms of connections
```
--out-peers 1
--in-peers 1
```
- added some network chaos using https://chaos-mesh.org/docs/run-a-chaos-experiment/ (not sure if it's helped)

Btw, today I've faced grandpa stuck twice. Attaching the logs of the last run with debug mode.
[grandpa-reproduced.txt](https://github.com/user-attachments/files/16440659/grandpa-reproduced.txt)

**Comment by dmitrylavrenov** [comment]
Logs from another node - just to double check smth maybe.
[node-1.txt](https://github.com/user-attachments/files/16440797/node-1.txt)

**Comment by dmitrylavrenov** [comment]
Status update

Still working on `chain-load-test` k8s-based tool that allows to run substrate-based networks with different peers configs and some network chaos experiments (https://chaos-mesh.org).

Current plan is to run different load tests this week trying to reproduce faced issue.

**Comment by bkchr** [comment]
> Still working on implementing our own `chain-load-test` k8s-based tool that allows to run substrate-based networks with different peers configs and some network chaos experiments (https://chaos-mesh.org).

Why not zombienet?

**Comment by dmitrylavrenov** [comment]
> > Still working on implementing our own `chain-load-test` k8s-based tool that allows to run substrate-based networks with different peers configs and some network chaos experiments (https://chaos-mesh.org).
> 
> Why not zombienet?

Will prepare the detailed answer a little bit later.

**Comment by dmitrylavrenov** [comment]
Status update

We were able to prepare a such config of our `chain-load-test` k8s-based tool that reproduces the exact issue we faced even with just 9 nodes.
![image](https://github.com/user-attachments/assets/9f7078de-1727-4eeb-81a3-2941f2e04633)
![image](https://github.com/user-attachments/assets/622e9af7-dee2-48c6-844d-c150c762b4dd)
![image](https://github.com/user-attachments/assets/0c0912ee-aee2-4641-8ccf-f84aea590bec)

Usually it requires less than 1 hour. 

[reproduced-grandpa-issue-logs-1.txt](https://github.com/user-attachments/files/16627681/reproduced-grandpa-issue-logs-1.txt)
[reproduced-grandpa-issue-logs-2.txt](https://github.com/user-attachments/files/16627682/reproduced-grandpa-issue-logs-2.txt)
[reproduced-grandpa-issue-logs.txt](https://github.com/user-attachments/files/16627683/reproduced-grandpa-issue-logs.txt)

Next step is preparing an image containing the fix and run tests again.

**Comment by MOZGIII** [comment]
On zombienet: in short, we tired it, and had issues with it.

The practical issues that we had was it rolled out too slow in our k8s testing environment, and took forever to deploy 1000 nodes (which we ran for testing some time ago).
Also, we dig deeper and found that it does not provide features besides reading the logs and running assertions on those logs, even even that was heavily unoptimized for the scale of testing we needed.
 
We also did look under the hood of zombienet, and found it substantially overengineering to our taste: supporting multiple execution environments (besides k8s) is just not necessary for a tool like this, in our collective opinion.

Ultimately, we decided to go agains fixing zombienet issues and make our own thing. It is very basic so far, but much more convenient for us to use, and with it we were actually able to reproduce the finality stalls. Not from the get go, and we'd probably be able alter a zombienet setup in a similar way - but with zombienet it would be unlikely that we'd be able to integrate our k8s-specific setup into the upstream.

Compared to zombienet, our solution does not have the evens model just yet, and doesn't parse the logs - but we don't need it, although it will be not too difficult to add if we decide to.

We'll can do a showcase if you're interested, as it is in a private repo for now. We'll make it public soon (the soon tm kind of soon - no eta).

**Comment by dmitrylavrenov** [comment]
> On zombienet: in short, we tired it, and had issues with it.
> 
> The practical issues that we had was it rolled out too slow in our k8s testing environment, and took forever to deploy 1000 nodes (which we ran for testing some time ago). Also, we dig deeper and found that it ~does not provide features besides reading the logs and running assertions on those logs~, and even that was heavily unoptimized for the scale of testing we needed.
> 
> We also did look under the hood of zombienet, and found it substantially overengineering to our taste: supporting multiple execution environments (besides k8s) is just not necessary for a tool like this, in our collective opinion.
> 
> Ultimately, we decided to go agains fixing zombienet issues and make our own thing. It is very basic so far, but much more convenient for us to use, and with it we were actually able to reproduce the finality stalls. Not from the get go, and we'd probably be able alter a zombienet setup in a similar way - but with zombienet it would be unlikely that we'd be able to integrate our k8s-specific setup into the upstream. We are quite satisfied with the results so far, as we can proceed with the work on fixing this bug knowing we have means to reproduce the issue.
> 
> Compared to zombienet, our solution does not have the evens model just yet, and doesn't parse the logs - but we don't need it, although it will be not too difficult to add if we decide to.
> 
> We'll can do a showcase if you're interested, as it is in a private repo for now. We'll make it public soon (the soon tm kind of soon - no eta).
> 
> UPD: our initial motivation for trying zombienet was to run a test cluster with a lot of nodes (`1000`, `2000`, `5000`, ...) as we are preparing to grow our validators headcount.

I can add some important items from practical usage:
- it was difficult to customize settings to make it working for networks with different SS58-prefix. Maybe it's already improved, but was needed to do some changes (the version I used in April-May) in the source code and rebuild by myself the tool.
- It's not possible to rerun failed pods keeping running good ones. All time you need to rerun the network from clean. As a result, sometimes the test with 1000 nodes take almost forever as setup is terminated if an image for some pod were not able to be pulled for some networks reason.

**Comment by dmitrylavrenov** [comment]
Status update

@bkchr @andresilva we have great news! 
We were able to test fixed version where we faced the same issue. But the consensus wasn't stucked and continued working as usual! Tested twice. You can check the logs :)

[grandpa-fix-logs.txt](https://github.com/user-attachments/files/16659556/grandpa-fix-logs.txt)
[grandpa-fix-logs-1.txt](https://github.com/user-attachments/files/16659555/grandpa-fix-logs-1.txt)

**Comment by dmitrylavrenov** [comment]
@MOZGIII I think we can close the issue and open the new one to backport the fix and shipped to our mainnet?

**Comment by andresilva** [comment]
Thanks for the thorough testing 👌

**Comment by MOZGIII** [comment]
> @MOZGIII I think we can close the issue and open the new one to backport the fix and ship to our mainnet?

Yes.

The investigation is now finished, and we were able to identify the bug, theorize and implement a fix, reproduce the bug reliably in a controlled environment, apply the fix and ensure the bug does not reproduce under the same conditions anymore, and that there are no other surprising effects from applying the fix.

We are now working on releasing the fix on the Humanode network.

Thanks everyone for taking part in this work!
