### ISSUE TITLE
Improve `EvmParams` configuration based on adding EVM

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#246]
As a follow up of #214 

- [x] Split`EvmParams` into EvmParams and EthereumRpcParams - with EvmParams containing only the settings required for the basic chain functionality (currently only target_gas_price), and the EthereumRpcParams to contain the RPC-related params, so that when the RPCs are not enabled these params can be omitted.

- [ ] `target_gas_price` should be a mandatory parameter (as in - it's not an optional value in a sense of the EVM runtime). The Evm is used as an Option outside, but this should always be present.

We can split this similarly to the changes to the cli args parser.

**Comment by MOZGIII** [comment]
This `target_gas_price` parameter is obsolete with https://github.com/humanode-network/humanode/pull/714
