### ISSUE TITLE
Think about `VotingRules` for `grandpa`

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#365]
At the current moment we use default voting rules for grandpa. But there is a way to define a custom rules options like doing finalisation in every 50 blocks, etc.

[Here](https://github.com/paritytech/polkadot/blob/5f769dc27e81601c70abb5d87861faf0ca2914da/node/service/src/lib.rs#L1226) is an example from polkadot node.

**Comment by MOZGIII** [comment]
Relevant:
- https://github.com/humanode-network/humanode/pull/584
- https://github.com/humanode-network/substrate/commit/da3a34ff7861d9bb504d013f2ef89e8b0ce2017c
- https://github.com/humanode-network/substrate/commit/15e218a5c777b5e19fa7106be88f87852c3ac4a3
- https://github.com/paritytech/substrate/pull/13289
