### ISSUE TITLE
Proper try-runtime support

### ISSUE THREAD

**Issue by MOZGIII** [humanode-network/humanode#397]
Our node doesn't support `try-runtime` - a crucial feature that allows checking whether the runtime will work correctly when applied to a certain existing state. This includes not just the bare functionality of the new runtime, but also allows for extensive testing of the migration code, thus being very useful in the actual development process while implementing the changes to the pallets state - to make sure the migrations will work fine when applied to the already-running chain with the real data.

Having this feature was not so important for us this far, but once we'll be required to maintain a single chain (as in mainnet, vs resetting them on each new major release), having `try-runtime` will become a critical tool for ensuring the high quality of our work.

So, we need to implement proper support for the `try-runtime` on our chain.

We first implement the support at the `humanode-peer`, and make sure it works manually.

Step two would be including it into the CI, such that we build the code with `try-runtime` enabled

Step three would be us running some E2E tests at CI with it. This would require a certain refactor of the CI, as we would want to avoid wasting the CI builder resources of building the binaries within the E2E run, and instead pass them in from the dedicated builds runs, effectively reusing the build artifacts and thus saving the time and CPU cycles.

**Comment by dmitrylavrenov** [comment]
https://github.com/humanode-network/humanode/pull/633
