### ISSUE TITLE
Implement a TypeScript-based E2E test suite

### ISSUE THREAD

**Issue by MOZGIII** [humanode-network/humanode#660]
We need a more advanced interface for implementing various E2E tests:

- wight to fee logic tests
- Ethereum RPC tests
- etc

For this, we need an environment at which we'd be able to write the test code in the TypeScript language, have it type-checked, use the npm libraries like `@polkadotjs/api` and `ethers`.

---

Might be related:

- https://github.com/humanode-network/humanode/issues/599

**Comment by dmitrylavrenov** [comment]
@MOZGIII it's already merged, right?

**Comment by MOZGIII** [comment]
This is partially done by #717.
We should create a tracking issue for the TypeScript E2E testing efforts (i.e. adding more tests that are mentioned here) - and then we can close this one.

**Comment by MOZGIII** [comment]
Turns out we have https://github.com/humanode-network/humanode/issues/613 and https://github.com/humanode-network/humanode/issues/237 as separate issues, so this *can* actually be closed.
