### ISSUE TITLE
Gas estimate problem

### ISSUE THREAD

**Issue by tonycdot** [humanode-network/humanode#761]
<img width="795" alt="image" src="https://github.com/humanode-network/humanode/assets/69084044/1d3bd3c2-446a-4541-91ef-814c1e09e69a">

I made a call to this SC and it estimated gas like 
<img width="415" alt="image" src="https://github.com/humanode-network/humanode/assets/69084044/74167f03-7ad9-4850-8188-4406410e4350">

SM: 
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.17;

contract NullTest {
    function a(address payable addr) payable external {
        addr.transfer(msg.value);
    }
}
```

Deployed on `it6` on `0x07470B4486725c73a97bEb19893d45d4eBBc835f`.
Account that received tokens is `0x92a0b8847C32192A68Db5b004B7F12ecc8Fc394e` and it's not exist.
Value - `1000 Wei`.

Upon transaction final gas fee is significantly lower:
<img width="311" alt="image" src="https://github.com/humanode-network/humanode/assets/69084044/b92b9ff8-1639-4592-8777-50acdec9db67">

@MOZGIII

**Comment by dmitrylavrenov** [comment]
Interesintg... @MOZGIII @tonycdot 

Just run locally and I have the estimation gas around 1.4 HMND.
<img width="557" alt="image" src="https://github.com/humanode-network/humanode/assets/39522748/68d753bc-a05c-430a-baa9-1f8ecad47b98">

By the way, it's x3 than the real gas.

**Comment by dmitrylavrenov** [comment]
But it's equal to gas estimation units

<img width="344" alt="image" src="https://github.com/humanode-network/humanode/assets/39522748/63c5d55c-7ab3-4730-96bc-8cdb7357e283">

**Comment by dmitrylavrenov** [comment]
It6 has been checked as well.

<img width="549" alt="Screenshot 2023-09-06 at 11 34 04" src="https://github.com/humanode-network/humanode/assets/39522748/1ba8ebd0-b687-4e79-ae68-c19afcc94dcc">
<img width="355" alt="Screenshot 2023-09-06 at 11 34 46" src="https://github.com/humanode-network/humanode/assets/39522748/ba478bfc-cb06-4fb2-9a37-53b7f143410d">

**Comment by dmitrylavrenov** [comment]
Played with metamask settings and got the following 
<img width="428" alt="Screenshot 2023-09-06 at 11 44 22" src="https://github.com/humanode-network/humanode/assets/39522748/1f43bb1c-75c6-4a47-96e6-4449cef343dc">
<img width="566" alt="Screenshot 2023-09-06 at 11 46 21" src="https://github.com/humanode-network/humanode/assets/39522748/78289d51-f4c8-49aa-a4ff-7f040defa801">

**Comment by dmitrylavrenov** [comment]
On the gas estimates issue:

https://github.com/paritytech/frontier/issues/280
https://github.com/paritytech/frontier/pull/269 (this is some real bs, but might work as a short term hack)
https://github.com/oasisprotocol/oasis-sdk/issues/631
https://github.com/moonbeam-foundation/moonbeam/pull/244 (moonbeam issue)
https://github.com/rust-blockchain/evm/issues/8 - this is where everything points to

cc @MOZGIII

**Comment by dmitrylavrenov** [comment]
Done with https://github.com/humanode-network/humanode/pull/772.
