### ISSUE TITLE
Smart contract account gets created and deleted on every payable call

### ISSUE THREAD

**Issue by tonycdot** [humanode-network/humanode#762]
<img width="579" alt="image" src="https://github.com/humanode-network/humanode/assets/69084044/bb834027-0db9-45d9-a719-c71baf892d86">

`0x07470B4486725c73a97bEb19893d45d4eBBc835f` is the address with SC
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.17;

contract NullTest {
    function a(address payable addr) payable external {
        addr.transfer(msg.value);
    }
}
```
I called `a(0xA117eCb9C5a2D42f3a224C7cF3136ACBB7DE889D)`.
Address `0xA117eCb9C5a2D42f3a224C7cF3136ACBB7DE889D` did not exist.
Chain - `humanode:it6`.
BlockId - `481959`.

@MOZGIII

**Comment by dmitrylavrenov** [comment]
Done with https://github.com/humanode-network/humanode/pull/777
