### ISSUE TITLE
Smart contract can't get less than ED via payable function

### ISSUE THREAD

**Issue by tonycdot** [humanode-network/humanode#763]
SC:
```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.17;

contract NullTest {
    function a() payable external {}
}
```

This contract had 0 on balance. Sending 199 Wei results in error:
```
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
Returned error: {"jsonrpc":"2.0","error":"evm error: OutOfFund","id":6275260900206630}
```

---

After sending 1 eHMND to SC, I was able to send **any** value without an error.

SC deployed at `0x8bCe54ff8aB45CB075b044AE117b8fD91F9351aB`.
Chain - `humanode:it6`.
SC balance is `1,000,000,000,000,000,100` - 1 eHMND + 100 Wei.

@MOZGIII

**Comment by MOZGIII** [comment]
This was fixed by changing EVM ED to `1`.
